package semestr3.Pr8;

public enum DrinkTypeEnum {
    BEER, WINE, VODKA, BRANDY, CHAMPAGNE, WHISKEY, TEQUILA, RUM, VERMUTH, LIQUOR, JAGERMEISTER,
    JUICE, COFFEE, GREEN_TEA, BLACK_TEA, MILK, WATER, SODA;
}
